name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
        django-version: [2.2, 3.0, 3.1, 3.2]

        exclude:
          - python-version: 3.5
            django-version: 3.0

          - python-version: 3.5
            django-version: 3.1

          - python-version: 3.5
            django-version: 3.2

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          django-version: ${{ matrix.django-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install coveralls
          pip install "django~=${{ matrix.django-version }}.0"
#      - name: Run flake8
#        run: |
#          pip install flake8
#          flake8 --exclude=migrations,tests --ignore=E501,E241,E225,E128 .
#      - name: Run pycodestyle
#        run: |
#          pip install pycodestyle
#          pycodestyle --exclude=migrations,tests --ignore=E501,E241,E225,E128 .
      - name: Run test
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          DJANGO: ${{ matrix.django-version }}
        run: |
          coverage run --source=ipware manage.py test
      - name: Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}