name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}, django ${{ matrix.django-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
        django-version: [22, 30]

        exclude:
          - python-version: 3.5
            django-version: 30

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          django-version: ${{ matrix.django-version }}
       - run: pip install -e .
       - run: pip install pycodestyle
       - run: pip install flake8
       - run: pip install coveralls
       - name: Run test
          run: coverage run --source=ipware manage.py test